ci:
  autoupdate_branch: "2.2.x"
  autoupdate_schedule: monthly
default_language_version:
  # default language version for each language used in the repository
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ "--django" ]
      - id: trailing-whitespace
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.10.0
    hooks:
      - id: pyupgrade
        args: [ "--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus" ]
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.7.0
  #   hooks:
  #     - id: isort
  #       args:
  #         # - "--config-file=.isort.cfg"
  #         - "--profile=black"
  #         - "--multi-line=3"
  #         - "--line-length=88"
  #         - "--default-section=THIRDPARTY"
  #         - "--known-third-party="
  #         - "--known-first-party="
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - --line-length=80
          - --include='\.pyi?$'
          # these folders wont be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports (src, tests)
        files: "^(?!examples/)"
        args: ["--application-directories", "src"]
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [ "-iii", "-ll" ]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args:
          - "--max-line-length=92"
          - "--max-complexity=12"
          - "--select=B,C,E,F,W,T4,B9"
          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=E203,E266,F403" # E501,W503,E402,F401,C901,B950E712,F821,E711,B001,E722,B008
        additional_dependencies: [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.901
    hooks:
      - id: mypy
        # args: [--config-file=mypy.ini]
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        additional_dependencies: [
            # mypy dependencies
            djangorestframework-stubs,
            django-stubs,
            # runtime dependencies
            # ...
        ]
